server:
  port: 8080
  error:
    include-stacktrace: on_trace_param

logging:
  level:
    com.learning.eagleeye.*: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health.showDetails: always

  info:
    git.mode: full
