version: "3"

services:
  licensing-service:
    image: abaig316/eagleeye.licensing-service
    depends_on:
      - config-server
      - postgres
    environment:
      PROFILE: docker
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      CONFIGSERVER_HOST: config-server
      CONFIGSERVER_PORT: 8888
      CONFIGSERVER_URI: "http://config-server:8888"
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    ports:
      - "8080:8080"

  config-server:
    image: abaig316/eagleeye.config-server
    environment:
      PROFILE: docker
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    ports:
      - "8888:8888"
    depends_on:
      - gitea

  eureka-server:
    image: abaig316/eagleeye.eureka-server
    environment:
      PROFILE: docker
    ports:
      - "8761:8761"

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr@s
      POSTGRES_DB: eagleeye_local
    ports:
      - "5432:5432"

  gitea:
    image: gitea/gitea:1.8.3
    environment:
      USER_UID: 1000
      USER_GID: 1000
      DB_TYPE: postgres
      DB_HOST: postgres-gitea:5432
      DB_NAME: gitea
      DB_USER: gitea
      DB_PASSWD: gitea
    volumes:
      - gitea-data:/data
    ports:
      - "3000:3000"
      - "22:22"
    restart: always
    depends_on:
      - postgres-gitea

  postgres-gitea:
    image: postgres:12
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: gitea
    volumes:
    - postgres-gitea-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  gitea-data:
  postgres-gitea-data:
