version: "3"

services:
  licensing-service:
    image: abaig316/eagleeye.licensing-service
    depends_on:
      - authentication-service
      - eureka-server
      - config-server
      - postgres
      - redis
    environment:
      PROFILE: docker
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      EUREKASERVER_HOST: eureka-server
      EUREKASERVER_PORT: 8761
      EUREKASERVER_URI: "http://eureka-server:8761/eureka"
      CONFIGSERVER_PORT: 8888
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    ports:
      - "8080:8080"

  organization-service:
    image: abaig316/eagleeye.organization-service
    depends_on:
      - authentication-service
      - eureka-server
      - config-server
      - postgres
    environment:
      PROFILE: docker
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      EUREKASERVER_HOST: eureka-server
      EUREKASERVER_PORT: 8761
      EUREKASERVER_URI: "http://eureka-server:8761/eureka"
      CONFIGSERVER_PORT: 8888
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    ports:
      - "8081:8081"

  authentication-service:
    image: abaig316/eagleeye.authentication-service
    depends_on:
      - eureka-server
      - config-server
    environment:
      PROFILE: docker
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      EUREKASERVER_HOST: eureka-server
      EUREKASERVER_PORT: 8761
      EUREKASERVER_URI: "http://eureka-server:8761/eureka"
      CONFIGSERVER_PORT: 8888
    ports:
      - "8901:8901"

  zuul-server:
    image: abaig316/eagleeye.zuul-server
    environment:
      PROFILE: docker
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      EUREKASERVER_HOST: eureka-server
      EUREKASERVER_PORT: 8761
      EUREKASERVER_URI: "http://eureka-server:8761/eureka"
      CONFIGSERVER_PORT: 8888
    ports:
      - "5555:5555"
    depends_on:
      - eureka-server
      - config-server
      - licensing-service
      - organization-service
      - authentication-service

  config-server:
    image: abaig316/eagleeye.config-server
    environment:
      PROFILE: docker
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      EUREKASERVER_HOST: eureka-server
      EUREKASERVER_PORT: 8761
      EUREKASERVER_URI: "http://eureka-server:8761/eureka"
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
      - gitea

  eureka-server:
    image: abaig316/eagleeye.eureka-server
    environment:
      PROFILE: docker
    ports:
      - "8761:8761"

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr@s
      POSTGRES_DB: eagleeye_local
    ports:
      - "5432:5432"

  gitea:
    image: gitea/gitea:1.8.3
    environment:
      USER_UID: 1000
      USER_GID: 1000
      DB_TYPE: postgres
      DB_HOST: postgres-gitea:5432
      DB_NAME: gitea
      DB_USER: gitea
      DB_PASSWD: gitea
    volumes:
      - gitea-data:/data
    ports:
      - "3000:3000"
      - "22:22"
    restart: always
    depends_on:
      - postgres-gitea

  postgres-gitea:
    image: postgres:12
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: gitea
    volumes:
    - postgres-gitea-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:5
    ports:
      - "6379:6379"

volumes:
  gitea-data:
  postgres-gitea-data:
