server:
  port: 8081
  error:
    include-stacktrace: on_trace_param

security:
  oauth2:
    client:
      grant-type: client_credentials

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health.showDetails: always

  info:
    git.mode: full
