server:
  port: 8888

spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: http://localhost:3000/abdullah/config-repo.git
          searchPaths: "*"

        native:
          searchLocations:
          - classpath:/config/licensing-service
          - classpath:/config/organization-service
          - classpath:/config/zuul-server

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
